[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hamster_betting = "5nyLrZamcFzJNqKDxtNFKBaYD5XWTAx5UDFaLuZsZagN"

[programs.devnet]
hamster_betting = "5nyLrZamcFzJNqKDxtNFKBaYD5XWTAx5UDFaLuZsZagN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
